### ISSUE TITLE
Can't runm tlpui on Arch Linux

### ISSUE THREAD

**Issue by mariachini** [d4nj1/TLPUI#133]
It's not possible to run `tlpui`. Following errors is shown:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tlpui", line 33, in <module>
    sys.exit(load_entry_point('TLPUI==1.5.0.post7', 'gui_scripts', 'tlpui')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/tlpui", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for TLPUI
```
I'm using ArchLinux with kernel 6.3.2-arch1-1.

**Comment by mariachini** [comment]
Found solution by myself - I've reinstalled tlpui from aur, but this time I built all the packages once again.
