### ISSUE TITLE
TLPUI fails to start

### ISSUE THREAD

**Issue by medmedin2014** [d4nj1/TLPUI#136]
Running tlpui command returns:
```
Traceback (most recent call last):
  File "/usr/bin/tlpui", line 33, in <module>
    sys.exit(load_entry_point('TLPUI==1.5.0.post7', 'gui_scripts', 'tlpui')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tlpui/__main__.py", line 31, in main
    init_tlp_file_config()
  File "/usr/lib/python3.11/site-packages/tlpui/file.py", line 40, in init_tlp_file_config
    settings.tlpconfig_defaults = get_tlp_config_defaults(tlpversion)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tlpui/file.py", line 26, in get_tlp_config_defaults
    tlpconfig_defaults = extract_default_tlp_configs(f"{settings.workdir}/defaults/tlp-{tlpversion}.conf")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tlpui/filehelper.py", line 46, in extract_default_tlp_configs
    fileopener = open(filename)
                 ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/tlpui/defaults/tlp-1_6.conf'
```

```
tlpui: 1.5.0.7
tlp: 1.6.0
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.12-1-MANJARO (64-bit)
Graphics Platform: Wayland
```

**Comment by d4nj1** [comment]
Hi,
thanks for reporting. Please also see issue #135 

It would be nice if you could test if https://github.com/d4nj1/TLPUI/releases/tag/tlpui-1.6.0 works for you

Thanks in advance

**Comment by d4nj1** [comment]
This is fixed in the source code of this project now. You still have to wait until Manjaro builds and publishes a new version of TLPUI or wait until Flathub build system has released the new version and use this.

**Comment by medmedin2014** [comment]
@d4nj1 The latest version 1.6.0 was pushed today to Manjaro unstable branch, and the app starts without any issue. Thanks for the quick fix.
