### ISSUE TITLE
Crash when missing element in config file

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#21]
TLP 1.0 will remove the parameter RUNTIME_PM_ALL completely. When i start tlpui.py with a config file without RUNTIME_PM_ALL (no commented line either) i get:

    Traceback (most recent call last):
      File "./tlpui.py", line 26, in <module>
        window.add(create_main_box(window, defaultconfigpath, tlpconfig))
      File "/srv/share/project/Ubuntu/Package/tlp/tlpui.git/mainui.py", line 136, in create_main_box
        configbox = create_config_box(tlp_config_items)
      File "/srv/share/project/Ubuntu/Package/tlp/tlpui.git/configui.py", line 22, in create_config_box
        tlp_categories = get_tlp_categories(tlp_config_items)
      File "/srv/share/project/Ubuntu/Package/tlp/tlpui.git/configui.py", line 177, in get_tlp_categories
        tlpitem = tlpconfig[id]
    KeyError: 'RUNTIME_PM_ALL'

**Comment by d4nj1** [comment]
See commit
