### ISSUE TITLE
error at start ./tlpui.py

### ISSUE THREAD

**Issue by joksik** [d4nj1/TLPUI#23]
[joks@joks-pc TLPUI-master]$ ./tlpui.py
Traceback (most recent call last):
  File "./tlpui.py", line 26, in <module>
    window.add(create_main_box(window, defaultconfigpath, tlpconfig))
  File "/home/joks/Pobrane/TLPUI-master/mainui.py", line 136, in create_main_box
    configbox = create_config_box(tlp_config_items)
  File "/home/joks/Pobrane/TLPUI-master/configui.py", line 22, in create_config_box
    tlp_categories = get_tlp_categories(tlp_config_items)
  File "/home/joks/Pobrane/TLPUI-master/configui.py", line 177, in get_tlp_categories
    tlpitem = tlpconfig[id]
KeyError: 'TLP_DEFAULT_MODE'

**Comment by d4nj1** [comment]
This bug was fixed in #21. You seem not to be on the latest master code. Please pull latest changes.

**Comment by joksik** [comment]
i download as .zip file yesterday from this github so i have latest version

**Comment by d4nj1** [comment]
I'm glad I could help.
