### ISSUE TITLE
Can't build in 18.04

### ISSUE THREAD

**Issue by giovannicaligaris** [d4nj1/TLPUI#32]
I keep getting this error

```
python3 -m tlpui
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/tlpui/tlpui/__main__.py", line 8, in <module>
    from . import settings
  File "/usr/share/tlpui/tlpui/settings.py", line 45, in <module>
    tlpconfigfile = config['default']['tlpconfigfile']
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'tlpconfigfile'
```

**Comment by d4nj1** [comment]
Hi,
seems like your tlpui config file is not as expected.
This file is located in your home folder under .config/tlpui/tlpui.cfg and should look like this:

```
[default]
language = en_EN
tlpconfigfile = /etc/default/tlp
activecategorie = 0
windowxsize = 900
windowysize = 600
```

Please adapt to this structure, or simply delete this file and let tlpui create a new one on next start.
Let me known if you have any further problems.

**Comment by giovannicaligaris** [comment]
It worked, thanks!

**Comment by d4nj1** [comment]
Glad I could help.
