### ISSUE TITLE
Not starting in manjaro

### ISSUE THREAD

**Issue by peteole** [d4nj1/TLPUI#58]
After a python update, the application does no more start in manjaro.

**Comment by d4nj1** [comment]
Hi,
can you share any errors when starting the application? Can you please provide the terminal output of:

`python3 --version`

and

`tlpui`

**Comment by peteole** [comment]
Hi, thank you for the fast answer!
```
tlpui

(__main__.py:24621): Gtk-WARNING **: 21:21:24.132: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(__main__.py:24621): Gtk-WARNING **: 21:21:24.132: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(__main__.py:24621): Gtk-WARNING **: 21:21:24.133: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/usr/share/tlp/tlp-func-base: line 351: /etc/default/tlp: Permission denied
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tlpui/tlpui/__main__.py", line 8, in <module>
    from . import settings
  File "/opt/tlpui/tlpui/settings.py", line 73, in <module>
    tlpconfigfile = get_tlp_config_file()
  File "/opt/tlpui/tlpui/settings.py", line 46, in get_tlp_config_file
    currentconfig = check_output(["tlp-stat", "-c"]).decode(sys.stdout.encoding)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tlp-stat', '-c']' returned non-zero exit status 1.
```

**Comment by peteole** [comment]
And it's Python 3.7.4

**Comment by d4nj1** [comment]
Hi,
it seems like **/etc/default/tlp** may not have the right file permissions.

It would be nice if you could provide the terminal output of:

`ls -la /etc/default/tlp`

On my system the file has permission **-rw-r--r--** (644)

**Comment by peteole** [comment]
On my system it's
```
ls -la /etc/default/tlp
-rw------- 1 root root 11820  8. Apr 2019  /etc/default/tlp
```
This seems to be the problem. If I run it as sudo, it works!

**Comment by d4nj1** [comment]
I think this issue is resolved from my point of view.
