### ISSUE TITLE
No such file or directory: 'tlp-usblist' upon clicking USB Blacklist,dialogue box doesn't appear 

### ISSUE THREAD

**Issue by kortewegdevries** [d4nj1/TLPUI#71]
Issue is both in current git master and ppa version. Upon clicking `USB_BLACKLIST` "Edit" the dialogue box doesn't appear and terminal spam:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tlpui/ui_config_objects/gtkusblist.py", line 32, in edit_list
    tlpusblist = check_output(["tlp-usblist"]).decode(sys.stdout.encoding)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tlp-usblist'
```
Details:
```
 Kernel: 5.4.0-40-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Xfce 4.14.2 Distro: Ubuntu 20.04 LTS (Focal Fossa) 

tlp: 1.3.1-2 from Ubuntu repo
Python 3.8.2
```

**Comment by kortewegdevries** [comment]
Temporary fix for git, point to absolute pathname in `tlpui/ui_config_objects/gtkusblist.py:    tlpusblist = check_output(["tlp-usblist"]).decode(sys.stdout.encoding)`,should I close this?

**Comment by d4nj1** [comment]
Hi @kortewegdevries.
Nice find!I missed the fact that **tlp-usblist** is not available anymore :see_no_evil: . I switched to the usage of **lsusb** command as this is also the suggested way to go for.
Please update to latest master and try again. Feedback is welcome.

Thanks in advance

**Comment by kortewegdevries** [comment]
Thanks, current master works. I forgot about `lsusb`, closing.
