### ISSUE TITLE
FileNotFoundError tlp-1_4.conf

### ISSUE THREAD

**Issue by Deckweiss** [d4nj1/TLPUI#93]
When I try to run tlpui it says:

```

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/tlpui/__main__.py", line 49, in <module>
    main()
  File "/usr/lib/python3/dist-packages/tlpui/__main__.py", line 26, in main
    init_tlp_file_config()
  File "/usr/lib/python3/dist-packages/tlpui/file.py", line 32, in init_tlp_file_config
    read_default_tlp_file_config('{}/defaults/tlp-{}.conf'.format(settings.workdir, tlpversion))
  File "/usr/lib/python3/dist-packages/tlpui/file.py", line 108, in read_default_tlp_file_config
    fileopener = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/tlpui/defaults/tlp-1_4.conf'

```

Kubuntu 20.10
TLP 1.4 alpha
Python 3.8.6

**Comment by d4nj1** [comment]
Hi @Deckweiss,
TLP 1.4 is not supported at the moment. I was not aware that it already reached alpha state. Will try to add support for the new version soon.

Kind regards

**Comment by d4nj1** [comment]
Hi @Deckweiss,
I just added/updated the required files. Could you please test if https://github.com/d4nj1/TLPUI/releases/tag/tlpui-1.4.0-alpha works for you?

**Comment by Deckweiss** [comment]
Works perfectly.

Thank you for your quick response!

**Comment by d4nj1** [comment]
Thanks for the feedback. Closing issue.
