### ISSUE TITLE
Missing dependency in the Ubuntu/Debian wiki page

### ISSUE THREAD

**Issue by ibrahimtuzlak0295** [d4nj1/TLPUI#96]
On a fresh Ubuntu 21.04 install (at least), building DEB will not work with the current dependency requirements alone:

```shell
sudo apt install python3-gi git python3-setuptools python3-stdeb
```

To correct this, add `dh-python` to the list, so that the complete command looks like this:

```shell
sudo apt install python3-gi git python3-setuptools python3-stdeb dh-python
```

The error from the log:

```shell
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
Traceback (most recent call last):
  File "/home/ibrahim/TLPUI/setup.py", line 4, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/bdist_deb.py", line 34, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/stdeb/command/sdist_dsc.py", line 137, in run
    build_dsc(debinfo,
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 1522, in build_dsc
    dpkg_buildpackage(*args, cwd=fullpath_repackaged_dirname)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 585, in dpkg_buildpackage
    process_command(args, cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 226, in process_command
    check_call(args, cwd=cwd)
  File "/usr/lib/python3/dist-packages/stdeb/util.py", line 59, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 3
```

**Comment by d4nj1** [comment]
Hi,
thanks for feedback. I just verified and updated the [wiki documentation](https://github.com/d4nj1/TLPUI/wiki/Install-instructions#ubuntudebian-family).

Kind regards
